### ISSUE TITLE
MySQL Support

### ISSUE THREAD

**Issue by izumiya** [jackskj/protoc-gen-map#3]
Hello, protoc-gen-map looks great! Any plans to add MySQL support?

**Comment by jackskj** [comment]
Hi izumiya, 
When creating the service server, you are expected to pass sql.DB connection from the database/sql package. MySQL connection with any driver will work.
You just have to make sure that your SQL is valid and your DB connections is working. 

However, version 0.4.0 will feature parametrized query support for postgresql, but I am not yet 100% sure if the same will be the case for MySQL.
