### ISSUE TITLE
Use QueryContext and ExecContext

### ISSUE THREAD

**Issue by ramonberrutti** [jackskj/protoc-gen-map#4]
First, an Excellent project.

To prevent queries running when the client finishes the connection we need to cancel the query.
WDYT using QueryContext?

I do the changes but I'm unable to run the tests. (Bazel errors)

Changes:

- templates/unary_response.go

```go
	{{ if eq .QueryType "Exec" }}
	_, err := m.DB.ExecContext(ctx, rawSql)
	if err != nil {

        // ...

	{{ else if eq .QueryType "Query" }}
	rows, err := m.DB.QueryContext(ctx, rawSql)
	if err != nil {
```

- templates/streaing_response.go

```go
	rows, err := m.DB.QueryContext(stream.Context(), rawSql)
	if err != nil {
```

Today all database support Context, if not have a fallback.

Thanks.

**Comment by jackskj** [comment]
Thank you. 
And yes good point, but can you elaborate how you intend to handle ctx and what exactly are you referring to by ‘client’? 
Do you mean the rpc client?

**Comment by jackskj** [comment]
Can I get your 2 cents on patch v0.4.1

**Comment by ramonberrutti** [comment]
Hi @jackskj :)
Sorry for the delay, yes.
The client is the client library (gRPC Client) calling the server. When I disconnect or cancel the request using (deadline timeout), I want to stop the query, and using context the driver handles this for us.

**Comment by jackskj** [comment]
That’s right, version v0.4.1 propagates the context to the query so that it does not have to run if client drops.

**Comment by jackskj** [comment]
can you take a look at examples/test and confirm that this resolves your issue. 

test:
https://github.com/jackskj/protoc-gen-map/blob/952003473db91947d59fdab5665e9c713b4bceb7/mapper/mapper_test.go#L281 

streaming response:
https://github.com/jackskj/protoc-gen-map/blob/952003473db91947d59fdab5665e9c713b4bceb7/testdata/tests.pb.map.go#L3279

unary response:
https://github.com/jackskj/protoc-gen-map/blob/952003473db91947d59fdab5665e9c713b4bceb7/testdata/tests.pb.map.go#L3177

**Comment by ramonberrutti** [comment]
Yes @jackskj 

Thank you :)
